// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq43EWcxbR7QKezhsUUe0tdLW59EoGykc',
    appId: '1:322376422652:web:678a0de788fdc8fbb53379',
    messagingSenderId: '322376422652',
    projectId: 'remedi-example',
    authDomain: 'remedi-example.firebaseapp.com',
    storageBucket: 'remedi-example.appspot.com',
    measurementId: 'G-17NHNP05Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ41jheypNxBYNhU7AWSncvw49RRUmI4Y',
    appId: '1:322376422652:android:6ab966df74d688f8b53379',
    messagingSenderId: '322376422652',
    projectId: 'remedi-example',
    storageBucket: 'remedi-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IbIfWSM9_FuToZY5s08l7QKoCQ-kM5k',
    appId: '1:322376422652:ios:24d56c48073614c0b53379',
    messagingSenderId: '322376422652',
    projectId: 'remedi-example',
    storageBucket: 'remedi-example.appspot.com',
    iosClientId: '322376422652-e2qjq9rqmpmmrhmhf11t94u1e7gtsp3a.apps.googleusercontent.com',
    iosBundleId: 'com.remedi.example',
  );
}
