name: remedi_net
description: Dio Wrapper Plugin.
version: 0.3.1
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: '>=2.12.0 <0.4.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  # http api.
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  http_mock_adapter: ^0.3.2

flutter:
