name: remedi_net
description: Dio Wrapper Plugin.
version: 0.3.1
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: '^3.1.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  # http api.
  dio: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  http_mock_adapter: ^0.6.0

flutter:
